version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:2.16.2
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - internal
      - traefik-public
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`docker.games.tnp.me.uk`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
#      - "traefik.http.routers.portainer.tls.certresolver=leresolver"
      
      # Edge
#      - "traefik.http.routers.edge.rule=Host(`edge.games.tnp.me.uk`)"
#      - "traefik.http.routers.edge.entrypoints=web"
#      - "traefik.http.services.edge.loadbalancer.server.port=8000"
#      - "traefik.http.routers.edge.service=edge"
#      - "traefik.http.routers.edge.tls.certresolver=leresolver"

volumes:
  portainer_data:
