version: '3'

services:
  monitoror:
    # A container that exposes an API to show its IP address
    image: monitoror/monitoror
    container_name: monitoror
    hostname: status
    ports:
      - "8080:8080"
    volumes:
      - "./config.json:/etc/monitoror/config.json"
    environment:
      - "MO_CONFIG=/etc/monitoror/config.json"

#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.whoami.entrypoints=web,websecure"
#      - "traefik.http.routers.whoami.rule=Host(`whoami.games.tnp.me.uk`)"
#      - "traefik.http.routers.whoami.service=whoami"
#      - "traefik.http.services.whoami.loadbalancer.server.port=80"
#      - "traefik.http.routers.whoami.tls=true"
#      - "traefik.http.routers.whoami.tls.certresolver=leresolver"

