version: '3'

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    networks:
      - internal
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=Host(`whoami.games.tnp.me.uk`)"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
