version: '3'

services:
  nginx:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./data/certs:/etc/ssl/private"
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"
      - "./data/www:/var/www/html"
#  certbot:
#    container_name: certbot
#    hostname: certbot
#    image: certbot/certbot
#    volumes:
#      - "./data/certs:/etc/ssl/private"
#      - "./data/certbot/conf:/etc/letsencrypt"
#      - "./data/certbot/www:/var/www/certbot"
#      - "./data/www:/var/www/html"
